version: "3.9"
services:
  api:
    container_name: api
    build: .
    volumes:
      - type: bind
        source: ./app
        target: /app
    ports:
      - 8080:8080
    env_file:
      - ./.env
